server:
  port: 9003
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      mvc:
        routes[0]:
          id: INVENTORY-SERVICE
          predicates[0]: Path=/inventoryservice/api/v1/brands/**
          uri: lb://INVENTORY-SERVICE
        routes[1]:
          id: DISCOVERY-SERVER
          predicates[0]: Path=/eureka/web
          filters[0]: SetPath=/
          uri: http://localhost:8761
        routes[2]:
          id: CUSTOMER-SERVICE
          predicates[0]: Path=/customerservice/api/v1/customers**
          uri: lb://CUSTOMER-SERVICE
